name: grcov

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          rustup default nightly
          cargo install cargo-tarpaulin
          sed 's/^patch-xml = {.*}$/patch-xml = { git = "https:\/\/github.com\/VilNeo\/patch-xml", branch = "main" }/' Cargo.toml > grcov-Cargo.toml
          cp grcov-Cargo.toml Cargo.toml
          cargo tarpaulin --out Xml
          bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN